dir = "src/services"
lang = "TS"
organization_id = "ginger-society"
portal_refs_file = "src/shared/references.ts"
service_type = "Portal"

[services]

[portals_refs]

[urls]
dev = "http://localhost:3000"
prod = "http://localhost:8081"
stage = "https://gingersociety.org"
