import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gingerSidebar: [{ type: 'autogenerated', dirName: 'ginger-dj' }],
  gingerBookSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      items: [
        "ginger-book/introduction",
        "ginger-book/setup",
        "ginger-book/stories",
        "ginger-book/decorators"
      ],
    },
    {
      type: "category",
      label: "Features",
      items: [
        "ginger-book/css",
        "ginger-book/hotkeys",
        "ginger-book/mdx",
        "ginger-book/meta",
        "ginger-book/mock-date",
        "ginger-book/providers",
        "ginger-book/typescript",
        "ginger-book/visual-snapshots",
      ],
    },
    {
      type: "category",
      label: "Addons",
      items: [
        "ginger-book/addons",
        "ginger-book/a11y",
        "ginger-book/actions",
        "ginger-book/background",
        "ginger-book/controls",
        "ginger-book/links",
        "ginger-book/msw",
        "ginger-book/source",
        "ginger-book/width",
      ],
    },
    {
      type: "category",
      label: "Recipes",
      items: ["ginger-book/nextjs"],
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        "ginger-book/cli",
        "ginger-book/config",
        "ginger-book/programmatic",
        "ginger-book/babel",
        "ginger-book/http2",
      ],
    },
    {
      type: "category",
      label: "Help",
      items: [
        "ginger-book/troubleshooting",
        {
          type: "link",
          label: "Contributing",
          href: "https://github.com/tajo/ladle/blob/main/CONTRIBUTING.md",
        },
      ],
    },
  ],
  gingerDBSidebar: [{ type: 'autogenerated', dirName: 'ginger-db' }],
  gingerUISidebar: [{
    type: "category",
    label: "Getting Started",
    collapsible: false,
    items: [
      "ginger-ui/index",
      "ginger-ui/installation",
      "ginger-ui/icons",
    ],
  }, {
    type: 'category', label: 'Components', collapsible: false,
    items: [
      "ginger-ui/button",
      "ginger-ui/header",
      "ginger-ui/input",
      "ginger-ui/dropdown",
      "ginger-ui/loader",
      "ginger-ui/modal",
      "ginger-ui/skeleton",
      "ginger-ui/snackbar",
      "ginger-ui/accordion",
      "ginger-ui/tooltip",
      "ginger-ui/typography",
      "ginger-ui/textarea",
      "ginger-ui/tags",
      "ginger-ui/tabs",
      "ginger-ui/table",
      "ginger-ui/sideMenu",
    ],
  }],
};

export default sidebars;
