import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gingerSidebar: [{ type: 'autogenerated', dirName: 'ginger-dj' }],
  gingerBookSidebar: [{ type: 'autogenerated', dirName: 'ginger-book' }],
  gingerDBSidebar: [{ type: 'autogenerated', dirName: 'ginger-db' }],
};

export default sidebars;
